name: hr_app
description: A mobile HR application for employees and managers

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  intl: ^0.18.1
  firebase_core: ^2.16.0
  cloud_firestore: ^4.10.0
  firebase_messaging: ^14.7.4
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  geolocator: ^10.0.0
  google_maps_flutter: ^2.2.6
  pdfx: ^0.8.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600